"""
Master File Creator
===================
Combines two Item Usage Report Excel files (generated by filegenerator.py)
into a single master file.

The "before" file's quantity columns are renamed:
    Total Quantity  →  Before Marketing Period Quantity
    Total Case QTY  →  Before Marketing Period Case QTY

The "during" file's quantity columns are renamed:
    Total Quantity  →  During Marketing Period Quantity
    Total Case QTY  →  During Marketing Period Case QTY

The two files are merged side-by-side on a set of identifying columns
(MERGE_KEYS), so each row in the master file contains data from both
date ranges for the same distributor location + product combination.

Usage:
    1. Set BEFORE_FILE, DURING_FILE, and OUTPUT_FILE below.
    2. Run:  python master_file_creator.py
"""

import pandas as pd
import os

# =============================================================================
# CONFIG  –  Edit these before running
# =============================================================================

BEFORE_FILE = r"z:\\Shared\\GPO Operations\\GPO Analytics & Support\\Data Skills Learning\\GPO Analytics Python Trainings\\Daniel's Files\\DYMA Brands - Powdered Drink Mix Target List 2025-05-01 to 2025-08-31 on 2026-02-26 at 11-02.xlsx"   # ← path to the "before" date range Excel file
DURING_FILE = r"z:\\Shared\\GPO Operations\\GPO Analytics & Support\\Data Skills Learning\\GPO Analytics Python Trainings\\Daniel's Files\\DYMA Brands - Powdered Drink Mix Target List 2024-09-01 to 2024-12-31 on 2026-02-26 at 11-11.xlsx"   # ← path to the "during" date range Excel file
OUTPUT_DIR = r"z:\\Shared\\GPO Operations\\GPO Analytics & Support\\Data Skills Learning\\GPO Analytics Python Trainings\\Daniel's Files"   # ← directory where the master Excel file will be saved

SHEET_NAME = "ALL Item Level Detail"

# Columns used to match rows between the two files.
# These are the identifying columns (not metrics). Adjust if your files
# include or exclude optional columns (e.g. "In MIN File?").
MERGE_KEYS = [
    "Distributor Parent",
    "DSTR PA Platform ID",
    "Distributor House",
    "DSTR Platform ID",
    "Manufacturer",
    "MFR Platform ID",
    "MIN",
    "DIN",
    "GTIN",
    "MFR Product ID",
    "DSTR Product ID",
    "Pack Size",
    "Product Description",
    "Unit",
    "Middle Category",
    "Brand",
    "Brand Owner",
    "On MAP?",
    "SF Highest Group Name",
    "SF Highest Group PLID",
    "SF Location: Name",
    "SF Location: Platform ID",
    "SF Location: Account ID",
    "SF PA: Name",
    "SF PA: Platform ID",
    "SF PA: Account ID",
    "SF GPA: Name",
    "SF GPA: Platform ID",
    "SF GPA: Account ID",
    "SF GGPA: Name",
    "SF GGPA: Platform ID",
    "SF GGPA: Account ID",
    "SF Location: Market Sector",
    "SF Location: Market Segment",
    "SF Location: Menu Type",
    "SF Location: Billing Street",
    "SF Location: Billing City",
    "SF Location: Billing Postal Code",
    "SF Location: Billing State",
    "SF PA: GPO Brands-MAP",
    "SF PA: Subscription Tier",
    "SF PA: Channel Partners",
    "SF PA: Client Manager",
    "SF Highest Group: Channel Partner(s)",
    "SF Highest Group: DSTR Sales Rep",
    "SF Highest Group: Primary Contact",
    "SF Highest Group: Primary Contact Email",
    "SF Highest Group: Primary Contact Phone",
]

# =============================================================================
# COLUMN RENAMING MAPS
# =============================================================================

BEFORE_RENAMES = {
    "Total Quantity": "Before Marketing Period Quantity",
    "Total Case QTY": "Before Marketing Period Case QTY",
}

DURING_RENAMES = {
    "Total Quantity": "During Marketing Period Quantity",
    "Total Case QTY": "During Marketing Period Case QTY",
}

# =============================================================================
# HELPERS
# =============================================================================

def build_output_path(before_file, during_file, output_dir):
    """Generate an output filename from the common prefix of the two input filenames."""
    before_name = os.path.splitext(os.path.basename(before_file))[0]
    during_name = os.path.splitext(os.path.basename(during_file))[0]
    # Find the longest common prefix
    common = os.path.commonprefix([before_name, during_name]).rstrip(" -")
    if not common:
        common = before_name
    filename = f"{common} - MASTER.xlsx"
    return os.path.join(output_dir, filename)


def load_sheet(filepath, sheet_name):
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")
    print(f"Reading: {filepath}")
    df = pd.read_excel(filepath, sheet_name=sheet_name)
    print(f"  {len(df):,} rows, {len(df.columns)} columns")
    return df


def resolve_merge_keys(df_before, df_during, requested_keys):
    """Return only keys that exist in both DataFrames, warning about any missing."""
    before_cols = set(df_before.columns)
    during_cols = set(df_during.columns)
    valid = [k for k in requested_keys if k in before_cols and k in during_cols]
    missing = [k for k in requested_keys if k not in before_cols or k not in during_cols]
    if missing:
        print(f"  Warning: the following MERGE_KEYS were not found in both files and will be skipped:")
        for col in missing:
            print(f"    - {col}")
    if not valid:
        raise ValueError("No valid merge keys found. Check that MERGE_KEYS matches your file columns.")
    return valid


# =============================================================================
# MAIN
# =============================================================================

def create_master_file(before_file, during_file, output_dir, sheet_name=SHEET_NAME):
    output_file = build_output_path(before_file, during_file, output_dir)
    # --- Load ---
    df_before = load_sheet(before_file, sheet_name)
    df_during = load_sheet(during_file, sheet_name)

    # --- Rename quantity columns ---
    df_before = df_before.rename(columns=BEFORE_RENAMES)
    df_during = df_during.rename(columns=DURING_RENAMES)

    # --- Merge ---
    merge_keys = resolve_merge_keys(df_before, df_during, MERGE_KEYS)
    print(f"\nMerging on {len(merge_keys)} key column(s)...")

    # Outer join so rows present in only one file are still included.
    # Non-key columns that exist in both files (e.g. Total Weight, Total Price)
    # will get _before / _during suffixes automatically.
    master = pd.merge(
        df_before,
        df_during,
        on=merge_keys,
        how="outer",
        suffixes=("_before", "_during"),
    )
    print(f"  Master: {len(master):,} rows, {len(master.columns)} columns")

    # --- Save ---
    os.makedirs(output_dir, exist_ok=True)

    with pd.ExcelWriter(output_file, engine="xlsxwriter") as writer:
        master.to_excel(writer, sheet_name="Master", index=False)

        # Auto-fit column widths
        worksheet = writer.sheets["Master"]
        for i, col in enumerate(master.columns):
            max_len = max(master[col].astype(str).map(len).max(), len(col)) + 2
            worksheet.set_column(i, i, min(max_len, 60))

    print(f"\nSaved: {output_file}")


if __name__ == "__main__":
    if not BEFORE_FILE or not DURING_FILE or not OUTPUT_DIR:
        raise ValueError("Please set BEFORE_FILE, DURING_FILE, and OUTPUT_DIR in the CONFIG section.")
    create_master_file(BEFORE_FILE, DURING_FILE, OUTPUT_DIR)
